### ISSUE TITLE
Propose improvement at Google Summer of Code, maybe like or at Gnome initiative

### ISSUE THREAD

**Issue by hifron** [ubuntu/desktop-devel-feedback#6]
GNOME has its internship for Google Summer of Code ideas [proposal at its GitLab](https://gitlab.gnome.org/Teams/internship/project-ideas)

I think that maybe Ubuntu could something propose for GNOME or maybe mentor something or think what is wrong at current Desktop and do something with it not only alone or maybe some collaboration with Fedora...

especially **lsb** red hatish standard I think is not so properly defined for current Desktop(and what only about **xdg**...:) and may be cause a lot of hidden issues not only in Python or Snaps space with something like POSIX always, but somehow libs missing or behaviour defined :)...

**Comment by tim-hm** [comment]
This would be great to see, but currently we don't have the internal resources to lead an application.
